=== Rodez-IUT/dut-info2-filmprovider-Favettou/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ELEMENT librairie (entete, livre)>
    <!ENTITY % balises "(#PCDATA|strong|em|img)*">
        <!ELEMENT entete %balises; %copyright;>
        <!ENTITY copyright "&#xA9;Librairie &amp; Internet 2020">
        <!ELEMENT strong (#PCDATA)>
        <!ELEMENT em (#PCDATA)>
        <!ELEMENT img EMPTY>
        <!ATTLIST img src CDATA #REQUIRED
                      title CDATA #IMPLIED>
    <!ELEMENT  livre (titre, auteur*, description, prix)>
    <!ATTLIST livre num_ISBN ID #REQUIRED>
        <!ELEMENT titre (#PCDATA)>
        <!ELEMENT auteur (auteurs*|collectif)>
            <!ENTITY % appelation "(nom, prenom?)">
            <!ELEMENT auteurs %appelation;+>
                <!ELEMENT nom (#PCDATA)>
                <!ELEMENT prenom (#PCDATA)>
            <!ELEMENT collectif (direction, membre)
                <!ELEMENT direction %appelation;>
                <!ELEMENT membre (#PCDATA)>
        <!ELEMENT description %balises;>
        <!ELEMENT prix (prixAchat)>
        <!ATTLIST prix tva #FIXED"5.5"
                       type ("HT" | TTC)
                       devise ("euros" | livres | dollars)>
            <!ELEMENT prixAchat (#PCDATA)>

            <!ATTLIST type (HT|TTC)>

=== Rodez-IUT/dut-info2-filmprovider-Favettou/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">

<librairie>
    <entete>
        <strong> Bienvenue dans cette librairie </strong>
        <em> Coucou </em>
        <!--&copyright;-->
    </entete>
    <livre num_ISBN="154-126">
        <titre>Autobiographie Adrien Garrouste</titre>
        <description> Mon autobiographie exceptionnelle, lisez l√† (svp)</description>
        <prix type="TTC">
            <prixAchat>35</prixAchat>
        </prix>
    </livre>
</librairie>
